# Whether to announce villager deaths globally or within an announcement radius.
# 'everyone'
# 'within-radius'
announce-to: "everyone"

# The circular radius in blocks around a villager within which players will see the death message.
# Only works when 'announce-to' is set to 'within-radius'.
announcement-radius: 1000