# The circular radius in blocks around an entity within which players will see the death message.
# Set to -1 to announce to everyone on the server.
announcement-radius: -1

death-messages:
  villagers:
    enabled: true
  wandering-traders:
    enabled: true
  named-entities:
    enabled: true
  pets:
    enabled: true

messages:
  include-coordinates: true
  discord-messages:
      enabled: false
      bot-token: ""
      channel-id: ""
