name: VillagerDeathMessagesPlugin
description: "A very simple plugin which displays death messages for villagers."
version: '${version}'
main: org.rolypolyvole.villagerdeaths.VillagerDeathMessagesPlugin
api-version: '1.20'
